# Site settings
title: "Amber. Студия профессионального озвучивания"
url: "vkStudioAmber.github.io"
baseurl: "/"

exclude:
  - LICENSE

# pages
paginate: 4
paginate_path: "/page-:num/"

# Build settings
markdown: kramdown
permalink: /post/:title
plugins:
  - jekyll-paginate
